spring.application.name=relay
server.port=8081


spring.datasource.url=jdbc:postgresql://localhost:5432/relay_db
spring.datasource.username=postgres
spring.datasource.password=@K4y4r4y4

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

relay.jwt-secret = rahasia-banget-nich
relay.jwt-expiration-in-day-access-token = 3
relay.jwt-issuer = abdulss

spring.data.redis.host=localhost
spring.data.redis.port=6379


# Jika Redis kamu pakai password
# spring.data.redis.password=secret

# Connection pool (opsional tapi direkomendasikan)
spring.data.redis.lettuce.pool.max-active=10
spring.data.redis.lettuce.pool.max-idle=5
spring.data.redis.lettuce.pool.min-idle=1

spring.mvc.hiddenmethod.filter.enabled=true